### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by mr-wh1tehat** [muhamed-didovic/tcdown#1]
npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/unicorn/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! file:///home/unicorn/node_modules/puppeteer/install.mjs:30
npm ERR!   const {downloadBrowser} = await (async () => {
npm ERR!                             ^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected reserved word
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-11-23T13_31_53_110Z-debug-0.log

any way to fix please

**Comment by muhamed-didovic** [comment]
hey @mr-wh1tehat is this issue related to install or something else, I need more info?

**Comment by muhamed-didovic** [comment]
hey @mr-wh1tehat, difficult to say what could be the issue on the first ball, but it seems you have issues with puppeteer, try to run it locally, I updated README file with some instructions, check and let me know how it goes
